"""Config package: colours, fonts, constants, sectors, symbols, and data config."""

from egx_radar.config.settings import (
    C,
    K,
    F_TITLE,
    F_HEADER,
    F_BODY,
    F_SMALL,
    F_MICRO,
    SECTORS,
    SYMBOLS,
    DECISION_PRIORITY,
    DATA_SOURCE_CFG,
    _data_cfg_lock,
    SOURCE_SETTINGS_FILE,
    get_sector,
    get_account_size,
    get_risk_per_trade,
    get_atr_exposure,
    get_max_per_sector,
)

__all__ = [
    "C",
    "K",
    "F_TITLE",
    "F_HEADER",
    "F_BODY",
    "F_SMALL",
    "F_MICRO",
    "SECTORS",
    "SYMBOLS",
    "DECISION_PRIORITY",
    "DATA_SOURCE_CFG",
    "_data_cfg_lock",
    "SOURCE_SETTINGS_FILE",
    "get_sector",
    "get_account_size",
    "get_risk_per_trade",
    "get_atr_exposure",
    "get_max_per_sector",
]
